# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'check_sanhak.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class check_sanhakUI(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(check_sanhakUI, self).__init__(parent)
        self.setupUi()
    def setupUi(self):
        # disable (but not hide) close button
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)
        self.setObjectName("Form")
        self.resize(615, 654)
        self.label_show_sanhak = QtWidgets.QLabel(self)
        self.label_show_sanhak.setGeometry(QtCore.QRect(220, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(26)
        self.label_show_sanhak.setFont(font)
        self.label_show_sanhak.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_sanhak.setObjectName("label_show_sanhak")
        self.label_show_B1_sanhak = QtWidgets.QLabel(self)
        self.label_show_B1_sanhak.setGeometry(QtCore.QRect(40, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B1_sanhak.setFont(font)
        self.label_show_B1_sanhak.setObjectName("label_show_B1_sanhak")
        self.label_show_B2_sanhak = QtWidgets.QLabel(self)
        self.label_show_B2_sanhak.setGeometry(QtCore.QRect(40, 280, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B2_sanhak.setFont(font)
        self.label_show_B2_sanhak.setObjectName("label_show_B2_sanhak")
        self.label_show_B4_sanhak = QtWidgets.QLabel(self)
        self.label_show_B4_sanhak.setGeometry(QtCore.QRect(40, 540, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B4_sanhak.setFont(font)
        self.label_show_B4_sanhak.setObjectName("label_show_B4_sanhak")
        self.label_show_B3_sanhak = QtWidgets.QLabel(self)
        self.label_show_B3_sanhak.setGeometry(QtCore.QRect(40, 410, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B3_sanhak.setFont(font)
        self.label_show_B3_sanhak.setObjectName("label_show_B3_sanhak")
        self.listWidget_show_B1_sanhak = QtWidgets.QListWidget(self)
        self.listWidget_show_B1_sanhak.setGeometry(QtCore.QRect(140, 120, 411, 101))
        self.listWidget_show_B1_sanhak.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B1_sanhak.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B1_sanhak.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B1_sanhak.setObjectName("listWidget_show_B1_sanhak")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_sanhak.addItem(item)
        self.listWidget_show_B2_sanhak = QtWidgets.QListWidget(self)
        self.listWidget_show_B2_sanhak.setGeometry(QtCore.QRect(140, 250, 411, 101))
        self.listWidget_show_B2_sanhak.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B2_sanhak.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B2_sanhak.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B2_sanhak.setObjectName("listWidget_show_B2_sanhak")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_sanhak.addItem(item)
        self.listWidget_show_B3_sanhak = QtWidgets.QListWidget(self)
        self.listWidget_show_B3_sanhak.setGeometry(QtCore.QRect(140, 380, 411, 101))
        self.listWidget_show_B3_sanhak.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B3_sanhak.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B3_sanhak.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B3_sanhak.setObjectName("listWidget_show_B3_sanhak")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_sanhak.addItem(item)
        self.listWidget_show_B4_sanhak = QtWidgets.QListWidget(self)
        self.listWidget_show_B4_sanhak.setGeometry(QtCore.QRect(140, 510, 411, 101))
        self.listWidget_show_B4_sanhak.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B4_sanhak.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B4_sanhak.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B4_sanhak.setObjectName("listWidget_show_B4_sanhak")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_sanhak.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_sanhak.addItem(item)
        self.pushButton_show_sanhak_back = QtWidgets.QPushButton(self)
        self.pushButton_show_sanhak_back.setGeometry(QtCore.QRect(270, 620, 93, 28))
        self.pushButton_show_sanhak_back.setObjectName("pushButton_show_sanhak_back")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "check_sanhak"))
        self.label_show_sanhak.setText(_translate("Form", "산학협동관"))
        self.label_show_B1_sanhak.setText(_translate("Form", "B1"))
        self.label_show_B2_sanhak.setText(_translate("Form", "B2"))
        self.label_show_B4_sanhak.setText(_translate("Form", "B4"))
        self.label_show_B3_sanhak.setText(_translate("Form", "B3"))
        __sortingEnabled = self.listWidget_show_B1_sanhak.isSortingEnabled()
        self.listWidget_show_B1_sanhak.setSortingEnabled(False)
        item = self.listWidget_show_B1_sanhak.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B1_sanhak.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B1_sanhak.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B1_sanhak.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B1_sanhak.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B1_sanhak.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B2_sanhak.isSortingEnabled()
        self.listWidget_show_B2_sanhak.setSortingEnabled(False)
        item = self.listWidget_show_B2_sanhak.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B2_sanhak.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B2_sanhak.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B2_sanhak.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B2_sanhak.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B2_sanhak.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B3_sanhak.isSortingEnabled()
        self.listWidget_show_B3_sanhak.setSortingEnabled(False)
        item = self.listWidget_show_B3_sanhak.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B3_sanhak.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B3_sanhak.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B3_sanhak.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B3_sanhak.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B3_sanhak.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B4_sanhak.isSortingEnabled()
        self.listWidget_show_B4_sanhak.setSortingEnabled(False)
        item = self.listWidget_show_B4_sanhak.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B4_sanhak.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B4_sanhak.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B4_sanhak.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B4_sanhak.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B4_sanhak.setSortingEnabled(__sortingEnabled)
        self.pushButton_show_sanhak_back.setText(_translate("Form", "돌아가기"))