# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'check_gongdae.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class check_gongdaeUI(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(check_gongdaeUI, self).__init__(parent)
        self.setupUi()
    def setupUi(self):
        # disable (but not hide) close button
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)
        self.setObjectName("Form")
        self.resize(615, 654)
        self.label_show_gongdae = QtWidgets.QLabel(self)
        self.label_show_gongdae.setGeometry(QtCore.QRect(220, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(26)
        self.label_show_gongdae.setFont(font)
        self.label_show_gongdae.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_gongdae.setObjectName("label_show_gongdae")
        self.label_show_B1_gongdae = QtWidgets.QLabel(self)
        self.label_show_B1_gongdae.setGeometry(QtCore.QRect(40, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B1_gongdae.setFont(font)
        self.label_show_B1_gongdae.setObjectName("label_show_B1_gongdae")
        self.label_show_B2_gongdae = QtWidgets.QLabel(self)
        self.label_show_B2_gongdae.setGeometry(QtCore.QRect(40, 280, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B2_gongdae.setFont(font)
        self.label_show_B2_gongdae.setObjectName("label_show_B2_gongdae")
        self.label_show_B3_gongdae = QtWidgets.QLabel(self)
        self.label_show_B3_gongdae.setGeometry(QtCore.QRect(40, 410, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B3_gongdae.setFont(font)
        self.label_show_B3_gongdae.setObjectName("label_show_B3_gongdae")
        self.listWidget_show_B1_gongdae = QtWidgets.QListWidget(self)
        self.listWidget_show_B1_gongdae.setGeometry(QtCore.QRect(140, 120, 411, 101))
        self.listWidget_show_B1_gongdae.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B1_gongdae.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B1_gongdae.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B1_gongdae.setObjectName("listWidget_show_B1_gongdae")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_gongdae.addItem(item)
        self.listWidget_show_B2_gongdae = QtWidgets.QListWidget(self)
        self.listWidget_show_B2_gongdae.setGeometry(QtCore.QRect(140, 250, 411, 101))
        self.listWidget_show_B2_gongdae.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B2_gongdae.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B2_gongdae.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B2_gongdae.setObjectName("listWidget_show_B2_gongdae")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_gongdae.addItem(item)
        self.listWidget_show_B3_gongdae = QtWidgets.QListWidget(self)
        self.listWidget_show_B3_gongdae.setGeometry(QtCore.QRect(140, 380, 411, 101))
        self.listWidget_show_B3_gongdae.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B3_gongdae.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B3_gongdae.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B3_gongdae.setObjectName("listWidget_show_B3_gongdae")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_gongdae.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_gongdae.addItem(item)
        self.pushButton_show_gongdae_back = QtWidgets.QPushButton(self)
        self.pushButton_show_gongdae_back.setGeometry(QtCore.QRect(250, 590, 93, 28))
        self.pushButton_show_gongdae_back.setObjectName("pushButton_show_gongdae_back")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "check_gongdae"))
        self.label_show_gongdae.setText(_translate("Form", "공과대학"))
        self.label_show_B1_gongdae.setText(_translate("Form", "B1"))
        self.label_show_B2_gongdae.setText(_translate("Form", "B2"))
        self.label_show_B3_gongdae.setText(_translate("Form", "B3"))
        __sortingEnabled = self.listWidget_show_B1_gongdae.isSortingEnabled()
        self.listWidget_show_B1_gongdae.setSortingEnabled(False)
        item = self.listWidget_show_B1_gongdae.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B1_gongdae.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B1_gongdae.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B1_gongdae.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B1_gongdae.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B1_gongdae.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B2_gongdae.isSortingEnabled()
        self.listWidget_show_B2_gongdae.setSortingEnabled(False)
        item = self.listWidget_show_B2_gongdae.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B2_gongdae.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B2_gongdae.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B2_gongdae.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B2_gongdae.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B2_gongdae.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B3_gongdae.isSortingEnabled()
        self.listWidget_show_B3_gongdae.setSortingEnabled(False)
        item = self.listWidget_show_B3_gongdae.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B3_gongdae.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B3_gongdae.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B3_gongdae.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B3_gongdae.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B3_gongdae.setSortingEnabled(__sortingEnabled)
        self.pushButton_show_gongdae_back.setText(_translate("Form", "돌아가기"))