# -*- coding: utf-8 -*-

# self implementation generated from reading ui file 'check_singong.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class check_singongUI(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(check_singongUI, self).__init__(parent)
        self.setupUi()
    def setupUi(self):
        # disable (but not hide) close button
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)
        self.setObjectName("Form")
        self.resize(615, 654)
        self.label_show_singong = QtWidgets.QLabel(self)
        self.label_show_singong.setGeometry(QtCore.QRect(220, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(26)
        self.label_show_singong.setFont(font)
        self.label_show_singong.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_singong.setObjectName("label_show_singong")
        self.label_show_B1_singong = QtWidgets.QLabel(self)
        self.label_show_B1_singong.setGeometry(QtCore.QRect(40, 150, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B1_singong.setFont(font)
        self.label_show_B1_singong.setObjectName("label_show_B1_singong")
        self.label_show_B2_singong = QtWidgets.QLabel(self)
        self.label_show_B2_singong.setGeometry(QtCore.QRect(40, 280, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B2_singong.setFont(font)
        self.label_show_B2_singong.setObjectName("label_show_B2_singong")
        self.label_show_B4_singong = QtWidgets.QLabel(self)
        self.label_show_B4_singong.setGeometry(QtCore.QRect(40, 540, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B4_singong.setFont(font)
        self.label_show_B4_singong.setObjectName("label_show_B4_singong")
        self.label_show_B3_singong = QtWidgets.QLabel(self)
        self.label_show_B3_singong.setGeometry(QtCore.QRect(40, 410, 61, 41))
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(18)
        self.label_show_B3_singong.setFont(font)
        self.label_show_B3_singong.setObjectName("label_show_B3_singong")
        self.listWidget_show_B1_singong = QtWidgets.QListWidget(self)
        self.listWidget_show_B1_singong.setGeometry(QtCore.QRect(140, 120, 411, 101))
        self.listWidget_show_B1_singong.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B1_singong.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B1_singong.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B1_singong.setObjectName("listWidget_show_B1_singong")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B1_singong.addItem(item)
        self.listWidget_show_B2_singong = QtWidgets.QListWidget(self)
        self.listWidget_show_B2_singong.setGeometry(QtCore.QRect(140, 250, 411, 101))
        self.listWidget_show_B2_singong.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B2_singong.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B2_singong.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B2_singong.setObjectName("listWidget_show_B2_singong")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B2_singong.addItem(item)
        self.listWidget_show_B3_singong = QtWidgets.QListWidget(self)
        self.listWidget_show_B3_singong.setGeometry(QtCore.QRect(140, 380, 411, 101))
        self.listWidget_show_B3_singong.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B3_singong.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B3_singong.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B3_singong.setObjectName("listWidget_show_B3_singong")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B3_singong.addItem(item)
        self.listWidget_show_B4_singong = QtWidgets.QListWidget(self)
        self.listWidget_show_B4_singong.setGeometry(QtCore.QRect(140, 510, 411, 101))
        self.listWidget_show_B4_singong.setFlow(QtWidgets.QListView.LeftToRight)
        self.listWidget_show_B4_singong.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_show_B4_singong.setGridSize(QtCore.QSize(80, 0))
        self.listWidget_show_B4_singong.setObjectName("listWidget_show_B4_singong")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_singong.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("-2002")
        font.setPointSize(11)
        item.setFont(font)
        self.listWidget_show_B4_singong.addItem(item)
        self.pushButton_show_singong_back = QtWidgets.QPushButton(self)
        self.pushButton_show_singong_back.setGeometry(QtCore.QRect(250, 620, 93, 28))
        self.pushButton_show_singong_back.setObjectName("pushButton_show_singong_back")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "check_singong"))
        self.label_show_singong.setText(_translate("Form", "신공학관"))
        self.label_show_B1_singong.setText(_translate("Form", "B1"))
        self.label_show_B2_singong.setText(_translate("Form", "B2"))
        self.label_show_B4_singong.setText(_translate("Form", "B4"))
        self.label_show_B3_singong.setText(_translate("Form", "B3"))
        __sortingEnabled = self.listWidget_show_B1_singong.isSortingEnabled()
        self.listWidget_show_B1_singong.setSortingEnabled(False)
        item = self.listWidget_show_B1_singong.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B1_singong.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B1_singong.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B1_singong.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B1_singong.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B1_singong.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B2_singong.isSortingEnabled()
        self.listWidget_show_B2_singong.setSortingEnabled(False)
        item = self.listWidget_show_B2_singong.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B2_singong.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B2_singong.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B2_singong.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B2_singong.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B2_singong.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B3_singong.isSortingEnabled()
        self.listWidget_show_B3_singong.setSortingEnabled(False)
        item = self.listWidget_show_B3_singong.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B3_singong.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B3_singong.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B3_singong.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B3_singong.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B3_singong.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget_show_B4_singong.isSortingEnabled()
        self.listWidget_show_B4_singong.setSortingEnabled(False)
        item = self.listWidget_show_B4_singong.item(0)
        item.setText(_translate("Form", "      0      "))
        item = self.listWidget_show_B4_singong.item(1)
        item.setText(_translate("Form", "      1      "))
        item = self.listWidget_show_B4_singong.item(2)
        item.setText(_translate("Form", "      2      "))
        item = self.listWidget_show_B4_singong.item(3)
        item.setText(_translate("Form", "      3      "))
        item = self.listWidget_show_B4_singong.item(4)
        item.setText(_translate("Form", "      4      "))
        self.listWidget_show_B4_singong.setSortingEnabled(__sortingEnabled)
        self.pushButton_show_singong_back.setText(_translate("Form", "돌아가기"))